
trigger:
- main

pool:
  name: AbhiPOOL

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'AbhiSC'
    backendAzureRmStorageAccountName: 'abhibknd'
    backendAzureRmContainerName: 'abhibkndcon'
    backendAzureRmKey: 'abhipipe1.tfstate'
