
trigger:
- main

pool:
  name: AbhiPOOL

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'AbhiSC'
    backendAzureRmResourceGroupName: 'ab_bknd'
    backendAzureRmStorageAccountName: 'abhibknd'
    backendAzureRmContainerName: 'abhibkndcon'
    backendAzureRmKey: 'abhi1.tfstate'
